// Code generated by "stringer -type=Operator"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SUM-43]
	_ = x[SUB-45]
	_ = x[PROD-42]
	_ = x[DIV-47]
	_ = x[XOR-94]
	_ = x[OR-124]
	_ = x[NOT-126]
	_ = x[AND-38]
	_ = x[MOD-37]
	_ = x[ASSIGN-61]
	_ = x[LPAREN-40]
	_ = x[RPAREN-41]
}

const (
	_Operator_name_0 = "MODAND"
	_Operator_name_1 = "LPARENRPARENPRODSUM"
	_Operator_name_2 = "SUB"
	_Operator_name_3 = "DIV"
	_Operator_name_4 = "ASSIGN"
	_Operator_name_5 = "XOR"
	_Operator_name_6 = "OR"
	_Operator_name_7 = "NOT"
)

var (
	_Operator_index_0 = [...]uint8{0, 3, 6}
	_Operator_index_1 = [...]uint8{0, 6, 12, 16, 19}
)

func (i Operator) String() string {
	switch {
	case 37 <= i && i <= 38:
		i -= 37
		return _Operator_name_0[_Operator_index_0[i]:_Operator_index_0[i+1]]
	case 40 <= i && i <= 43:
		i -= 40
		return _Operator_name_1[_Operator_index_1[i]:_Operator_index_1[i+1]]
	case i == 45:
		return _Operator_name_2
	case i == 47:
		return _Operator_name_3
	case i == 61:
		return _Operator_name_4
	case i == 94:
		return _Operator_name_5
	case i == 124:
		return _Operator_name_6
	case i == 126:
		return _Operator_name_7
	default:
		return "Operator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
